import { WorkplaceStage } from "../types";

export interface WorkplaceZoneTheme {
  id: string;
  name: string;
  shortName: string;
  emoji: string;
  iconName: string;
  category: "workplace" | "chill_spot" | "cyber_synth" | "luxe_minimal" | "tactical_sre" | "nature_focus";
  themeFamily?: "cyber" | "luxe" | "tactical" | "nature" | "classic";
  vibe: string;
  tagline: string;
  buffMultiplier: string;
  colors: {
    primary: string; // hex
    secondary: string; // hex
    accentText: string; // tailwind class
    accentTextHover: string;
    accentBg: string;
    accentBgSoft: string;
    accentBorder: string;
    accentBorderStrong: string;
    accentGlow: string;
    ambientAura: string;
    appBgGradient: string;
    cardBg: string;
    headerGradient: string;
    sidebarActiveBg: string;
    sidebarActiveText: string;
    sidebarActiveBorder: string;
    buttonGradient: string;
    buttonGradientHover: string;
    badgeBg: string;
    badgeText: string;
    badgeBorder: string;
  };
  ambientTrack: "cyber_hum" | "zen_rain" | "lofi_beats" | "binaural_432" | "cafe_chatter" | "vault_pulse";
  ambientTrackTitle: string;
}

export const WORKPLACE_ZONE_THEMES: Record<string, WorkplaceZoneTheme> = {
  // 1. NEON GRID 2099
  "theme-cyberpunk-2099": {
    id: "theme-cyberpunk-2099",
    name: "Cyberpunk 2099 / Neon Grid",
    shortName: "Neon Grid 2099",
    emoji: "⚡",
    iconName: "Zap",
    category: "cyber_synth",
    themeFamily: "cyber",
    vibe: "High-Voltage Overclock",
    tagline: "Electric cyan & hot magenta with synthetic scanlines and neural overclocking",
    buffMultiplier: "+45% Neural Throughput & Execution Velocity",
    colors: {
      primary: "#00f3ff",
      secondary: "#ff007f",
      accentText: "text-cyan-300",
      accentTextHover: "hover:text-cyan-200",
      accentBg: "bg-cyan-400",
      accentBgSoft: "bg-cyan-400/10",
      accentBorder: "border-cyan-400/40",
      accentBorderStrong: "border-cyan-300/80",
      accentGlow: "shadow-[0_0_40px_rgba(0,243,255,0.35)]",
      ambientAura: "radial-gradient(ellipse 90% 55% at 50% -20%, rgba(0,243,255,0.25), rgba(255,0,127,0.12), transparent)",
      appBgGradient: "from-slate-950 via-[#030d22] to-slate-950",
      cardBg: "bg-slate-900/85",
      headerGradient: "from-cyan-950/50 via-slate-900/90 to-fuchsia-950/40",
      sidebarActiveBg: "bg-gradient-to-r from-cyan-500/20 to-fuchsia-500/20",
      sidebarActiveText: "text-cyan-300",
      sidebarActiveBorder: "border-cyan-400/60",
      buttonGradient: "from-cyan-400 via-blue-600 to-fuchsia-600",
      buttonGradientHover: "hover:from-cyan-300 hover:via-blue-500 hover:to-fuchsia-500",
      badgeBg: "bg-cyan-500/25",
      badgeText: "text-cyan-200",
      badgeBorder: "border-cyan-400/50",
    },
    ambientTrack: "cyber_hum",
    ambientTrackTitle: "High-Frequency Sub-Bass & Neon Plasma Arpeggios",
  },

  // 2. TOKYO SYNTHWAVE
  "theme-tokyo-synthwave": {
    id: "theme-tokyo-synthwave",
    name: "Tokyo Synthwave / Midnight Ultraviolet",
    shortName: "Tokyo Synthwave",
    emoji: "🌆",
    iconName: "Radio",
    category: "cyber_synth",
    themeFamily: "cyber",
    vibe: "Outrun Synthwave",
    tagline: "Deep midnight retro-wave with warm purple neon, twilight grid aesthetics, and analog warmth",
    buffMultiplier: "+35% Creative Workflow Synthesis & Fluency",
    colors: {
      primary: "#a855f7",
      secondary: "#f43f5e",
      accentText: "text-purple-300",
      accentTextHover: "hover:text-purple-200",
      accentBg: "bg-purple-500",
      accentBgSoft: "bg-purple-500/15",
      accentBorder: "border-purple-500/40",
      accentBorderStrong: "border-purple-400/80",
      accentGlow: "shadow-[0_0_40px_rgba(168,85,247,0.3)]",
      ambientAura: "radial-gradient(ellipse 90% 55% at 50% -20%, rgba(168,85,247,0.25), rgba(244,63,94,0.12), transparent)",
      appBgGradient: "from-slate-950 via-[#1a0429] to-slate-950",
      cardBg: "bg-slate-900/85",
      headerGradient: "from-purple-950/50 via-slate-900/90 to-rose-950/40",
      sidebarActiveBg: "bg-gradient-to-r from-purple-500/20 to-rose-500/20",
      sidebarActiveText: "text-purple-300",
      sidebarActiveBorder: "border-purple-400/60",
      buttonGradient: "from-purple-500 via-pink-600 to-rose-600",
      buttonGradientHover: "hover:from-purple-400 hover:via-pink-500 hover:to-rose-500",
      badgeBg: "bg-purple-500/25",
      badgeText: "text-purple-200",
      badgeBorder: "border-purple-400/50",
    },
    ambientTrack: "lofi_beats",
    ambientTrackTitle: "Analog Synth Pads & Lo-Fi Tape Warmth",
  },

  // 3. OBSIDIAN GOLD
  "theme-obsidian-gold": {
    id: "theme-obsidian-gold",
    name: "Obsidian Sovereign & Champagne Gold",
    shortName: "Obsidian Gold",
    emoji: "👑",
    iconName: "Crown",
    category: "luxe_minimal",
    themeFamily: "luxe",
    vibe: "Executive Sovereign",
    tagline: "Ultra-luxurious obsidian carbon with brushed champagne gold trim and sovereign boardroom elegance",
    buffMultiplier: "+30% Enterprise Valuation & ROI Calculation",
    colors: {
      primary: "#f59e0b",
      secondary: "#eab308",
      accentText: "text-amber-300",
      accentTextHover: "hover:text-amber-200",
      accentBg: "bg-amber-500",
      accentBgSoft: "bg-amber-500/15",
      accentBorder: "border-amber-500/40",
      accentBorderStrong: "border-amber-400/80",
      accentGlow: "shadow-[0_0_40px_rgba(245,158,11,0.28)]",
      ambientAura: "radial-gradient(ellipse 90% 55% at 50% -20%, rgba(245,158,11,0.22), rgba(234,179,8,0.1), transparent)",
      appBgGradient: "from-stone-950 via-[#181104] to-stone-950",
      cardBg: "bg-stone-900/90",
      headerGradient: "from-amber-950/50 via-stone-900/90 to-yellow-950/30",
      sidebarActiveBg: "bg-gradient-to-r from-amber-500/20 to-yellow-500/15",
      sidebarActiveText: "text-amber-300",
      sidebarActiveBorder: "border-amber-400/60",
      buttonGradient: "from-amber-500 via-yellow-600 to-orange-600",
      buttonGradientHover: "hover:from-amber-400 hover:via-yellow-500 hover:to-orange-500",
      badgeBg: "bg-amber-500/25",
      badgeText: "text-amber-200",
      badgeBorder: "border-amber-400/50",
    },
    ambientTrack: "binaural_432",
    ambientTrackTitle: "Skyline Alpha Waves & Velvet Lounge Warmth",
  },

  // 4. ARCTIC FROST
  "theme-arctic-frost": {
    id: "theme-arctic-frost",
    name: "Arctic Frost / Glacial Titanium",
    shortName: "Arctic Glacial",
    emoji: "❄️",
    iconName: "Snowflake",
    category: "luxe_minimal",
    themeFamily: "luxe",
    vibe: "Sub-Zero Precision",
    tagline: "Pristine glacial glassmorphism, cold surgical slate, and distraction-free cognitive clarity",
    buffMultiplier: "+30% Deep Analytical Reasoning & SRE Cooldown",
    colors: {
      primary: "#38bdf8",
      secondary: "#818cf8",
      accentText: "text-sky-300",
      accentTextHover: "hover:text-sky-200",
      accentBg: "bg-sky-400",
      accentBgSoft: "bg-sky-400/15",
      accentBorder: "border-sky-400/40",
      accentBorderStrong: "border-sky-300/80",
      accentGlow: "shadow-[0_0_40px_rgba(56,189,248,0.3)]",
      ambientAura: "radial-gradient(ellipse 90% 55% at 50% -20%, rgba(56,189,248,0.22), rgba(129,140,248,0.12), transparent)",
      appBgGradient: "from-slate-950 via-[#06162a] to-slate-950",
      cardBg: "bg-slate-900/85",
      headerGradient: "from-sky-950/50 via-slate-900/90 to-indigo-950/40",
      sidebarActiveBg: "bg-gradient-to-r from-sky-500/20 to-indigo-500/15",
      sidebarActiveText: "text-sky-300",
      sidebarActiveBorder: "border-sky-400/60",
      buttonGradient: "from-sky-400 via-blue-600 to-indigo-600",
      buttonGradientHover: "hover:from-sky-300 hover:via-blue-500 hover:to-indigo-500",
      badgeBg: "bg-sky-500/25",
      badgeText: "text-sky-200",
      badgeBorder: "border-sky-400/50",
    },
    ambientTrack: "zen_rain",
    ambientTrackTitle: "Glacial Wind Drone & Cryo Crystal Resonances",
  },

  // 5. EMERALD MATRIX
  "theme-emerald-matrix": {
    id: "theme-emerald-matrix",
    name: "Emerald Matrix / Bio-Hacker Forest",
    shortName: "Emerald Matrix",
    emoji: "🟩",
    iconName: "Terminal",
    category: "nature_focus",
    themeFamily: "nature",
    vibe: "Matrix Digital Rain",
    tagline: "Phosphorescent matrix green with deep cyber moss and hallucination suppression",
    buffMultiplier: "+40% Hallucination Suppression & Accuracy",
    colors: {
      primary: "#10b981",
      secondary: "#06b6d4",
      accentText: "text-emerald-300",
      accentTextHover: "hover:text-emerald-200",
      accentBg: "bg-emerald-500",
      accentBgSoft: "bg-emerald-500/15",
      accentBorder: "border-emerald-500/40",
      accentBorderStrong: "border-emerald-400/80",
      accentGlow: "shadow-[0_0_40px_rgba(16,185,129,0.3)]",
      ambientAura: "radial-gradient(ellipse 90% 55% at 50% -20%, rgba(16,185,129,0.22), rgba(6,182,212,0.12), transparent)",
      appBgGradient: "from-stone-950 via-[#021c12] to-stone-950",
      cardBg: "bg-stone-900/85",
      headerGradient: "from-emerald-950/50 via-stone-900/90 to-teal-950/40",
      sidebarActiveBg: "bg-gradient-to-r from-emerald-500/20 to-teal-500/15",
      sidebarActiveText: "text-emerald-300",
      sidebarActiveBorder: "border-emerald-400/60",
      buttonGradient: "from-emerald-500 via-teal-600 to-cyan-600",
      buttonGradientHover: "hover:from-emerald-400 hover:via-teal-500 hover:to-cyan-500",
      badgeBg: "bg-emerald-500/25",
      badgeText: "text-emerald-200",
      badgeBorder: "border-emerald-400/50",
    },
    ambientTrack: "zen_rain",
    ambientTrackTitle: "Matrix Digital Stream & Rain on Bamboo",
  },

  // 6. CLEAN SLATE TITANIUM
  "theme-clean-slate": {
    id: "theme-clean-slate",
    name: "Clean Slate Titanium / Studio Minimal",
    shortName: "Clean Slate Titanium",
    emoji: "🔲",
    iconName: "Layers",
    category: "luxe_minimal",
    themeFamily: "luxe",
    vibe: "Distraction-Free Minimal",
    tagline: "Monochrome surgical titanium slate and deep void — zero noise, pure engineering focus",
    buffMultiplier: "+25% Uncluttered Cognitive Bandwidth",
    colors: {
      primary: "#94a3b8",
      secondary: "#64748b",
      accentText: "text-slate-200",
      accentTextHover: "hover:text-white",
      accentBg: "bg-slate-400",
      accentBgSoft: "bg-slate-400/15",
      accentBorder: "border-slate-500/40",
      accentBorderStrong: "border-slate-300/60",
      accentGlow: "shadow-[0_0_30px_rgba(148,163,184,0.2)]",
      ambientAura: "radial-gradient(ellipse 90% 55% at 50% -20%, rgba(148,163,184,0.16), transparent)",
      appBgGradient: "from-slate-950 via-[#0a0e17] to-slate-950",
      cardBg: "bg-slate-900/90",
      headerGradient: "from-slate-900/90 via-slate-900/90 to-slate-950/90",
      sidebarActiveBg: "bg-slate-800/80",
      sidebarActiveText: "text-white",
      sidebarActiveBorder: "border-slate-400/60",
      buttonGradient: "from-slate-700 via-slate-800 to-slate-900",
      buttonGradientHover: "hover:from-slate-600 hover:via-slate-700 hover:to-slate-800",
      badgeBg: "bg-slate-800/80",
      badgeText: "text-slate-200",
      badgeBorder: "border-slate-600",
    },
    ambientTrack: "lofi_beats",
    ambientTrackTitle: "Muted White Noise & Mechanical Key Clicks",
  },

  // 7. SRE CYBER WAR ROOM
  "stage-war-room": {
    id: "stage-war-room",
    name: "SRE Cyber War Room",
    shortName: "Cyber War Room",
    emoji: "🛡️",
    iconName: "Server",
    category: "workplace",
    themeFamily: "tactical",
    vibe: "Cyber Alert",
    tagline: "High-throughput real-time incident resolution & infrastructure telemetry",
    buffMultiplier: "+25% SRE Incident Resolution Speed",
    colors: {
      primary: "#06b6d4", // cyan-500
      secondary: "#3b82f6", // blue-500
      accentText: "text-cyan-400",
      accentTextHover: "hover:text-cyan-300",
      accentBg: "bg-cyan-500",
      accentBgSoft: "bg-cyan-500/10",
      accentBorder: "border-cyan-500/30",
      accentBorderStrong: "border-cyan-500/60",
      accentGlow: "shadow-[0_0_35px_rgba(6,182,212,0.22)]",
      ambientAura: "radial-gradient(ellipse 80% 50% at 50% -20%, rgba(6,182,212,0.18), transparent)",
      appBgGradient: "from-slate-950 via-[#030c1e] to-slate-950",
      cardBg: "bg-slate-900/80",
      headerGradient: "from-cyan-950/40 via-slate-900/90 to-slate-950/90",
      sidebarActiveBg: "bg-cyan-500/15",
      sidebarActiveText: "text-cyan-400",
      sidebarActiveBorder: "border-cyan-500/40",
      buttonGradient: "from-cyan-500 via-blue-600 to-indigo-600",
      buttonGradientHover: "hover:from-cyan-400 hover:via-blue-500 hover:to-indigo-500",
      badgeBg: "bg-cyan-500/20",
      badgeText: "text-cyan-300",
      badgeBorder: "border-cyan-500/40",
    },
    ambientTrack: "cyber_hum",
    ambientTrackTitle: "Sub-Bass Server Core Hum & Fan Array",
  },
  "stage-zen-garden": {
    id: "stage-zen-garden",
    name: "Deep Focus Zen Garden & Dojo",
    shortName: "Zen Garden",
    emoji: "🎋",
    iconName: "Wind",
    category: "chill_spot",
    themeFamily: "nature",
    vibe: "Zen Oasis",
    tagline: "Tranquil sanctuary for deep cognitive tasks, hallucination suppression & clarity",
    buffMultiplier: "+30% Hallucination Suppression & Accuracy",
    colors: {
      primary: "#10b981", // emerald-500
      secondary: "#14b8a6", // teal-500
      accentText: "text-emerald-400",
      accentTextHover: "hover:text-emerald-300",
      accentBg: "bg-emerald-500",
      accentBgSoft: "bg-emerald-500/10",
      accentBorder: "border-emerald-500/30",
      accentBorderStrong: "border-emerald-500/60",
      accentGlow: "shadow-[0_0_35px_rgba(16,185,129,0.22)]",
      ambientAura: "radial-gradient(ellipse 80% 50% at 50% -20%, rgba(16,185,129,0.18), transparent)",
      appBgGradient: "from-stone-950 via-[#041d13] to-stone-950",
      cardBg: "bg-stone-900/80",
      headerGradient: "from-emerald-950/40 via-stone-900/90 to-stone-950/90",
      sidebarActiveBg: "bg-emerald-500/15",
      sidebarActiveText: "text-emerald-400",
      sidebarActiveBorder: "border-emerald-500/40",
      buttonGradient: "from-emerald-500 via-teal-600 to-green-600",
      buttonGradientHover: "hover:from-emerald-400 hover:via-teal-500 hover:to-green-500",
      badgeBg: "bg-emerald-500/20",
      badgeText: "text-emerald-300",
      badgeBorder: "border-emerald-500/40",
    },
    ambientTrack: "zen_rain",
    ambientTrackTitle: "432 Hz Theta Frequency & Bamboo Rain",
  },
  "stage-strategy-oasis": {
    id: "stage-strategy-oasis",
    name: "Executive Penthouse Strategy Deck",
    shortName: "Penthouse Deck",
    emoji: "🍸",
    iconName: "TrendingUp",
    category: "workplace",
    themeFamily: "luxe",
    vibe: "Deep Focus",
    tagline: "High-level planning, ROI synthesis, and cross-departmental coordination",
    buffMultiplier: "+20% Business Value & ROI Estimation",
    colors: {
      primary: "#f59e0b", // amber-500
      secondary: "#eab308", // yellow-500
      accentText: "text-amber-400",
      accentTextHover: "hover:text-amber-300",
      accentBg: "bg-amber-500",
      accentBgSoft: "bg-amber-500/10",
      accentBorder: "border-amber-500/30",
      accentBorderStrong: "border-amber-500/60",
      accentGlow: "shadow-[0_0_35px_rgba(245,158,11,0.22)]",
      ambientAura: "radial-gradient(ellipse 80% 50% at 50% -20%, rgba(245,158,11,0.18), transparent)",
      appBgGradient: "from-slate-950 via-[#1e1402] to-slate-950",
      cardBg: "bg-slate-900/80",
      headerGradient: "from-amber-950/40 via-slate-900/90 to-slate-950/90",
      sidebarActiveBg: "bg-amber-500/15",
      sidebarActiveText: "text-amber-400",
      sidebarActiveBorder: "border-amber-500/40",
      buttonGradient: "from-amber-500 via-yellow-600 to-orange-600",
      buttonGradientHover: "hover:from-amber-400 hover:via-yellow-500 hover:to-orange-500",
      badgeBg: "bg-amber-500/20",
      badgeText: "text-amber-300",
      badgeBorder: "border-amber-500/40",
    },
    ambientTrack: "binaural_432",
    ambientTrackTitle: "Binaural Alpha Waves & Skyline Ambience",
  },
  "stage-coffee-lounge": {
    id: "stage-coffee-lounge",
    name: "Rooftop Coffee Bar & Chill Spot",
    shortName: "Coffee Lounge",
    emoji: "☕",
    iconName: "Coffee",
    category: "chill_spot",
    themeFamily: "classic",
    vibe: "Social Cafe",
    tagline: "Casual social hangout, collaborative banter, and agent recharge station",
    buffMultiplier: "+20% Cross-Agent Synergy & Creativity",
    colors: {
      primary: "#f97316", // orange-500
      secondary: "#ea580c", // orange-600
      accentText: "text-orange-400",
      accentTextHover: "hover:text-orange-300",
      accentBg: "bg-orange-500",
      accentBgSoft: "bg-orange-500/10",
      accentBorder: "border-orange-500/30",
      accentBorderStrong: "border-orange-500/60",
      accentGlow: "shadow-[0_0_35px_rgba(249,115,22,0.22)]",
      ambientAura: "radial-gradient(ellipse 80% 50% at 50% -20%, rgba(249,115,22,0.18), transparent)",
      appBgGradient: "from-stone-950 via-[#210e03] to-stone-950",
      cardBg: "bg-stone-900/80",
      headerGradient: "from-orange-950/40 via-stone-900/90 to-stone-950/90",
      sidebarActiveBg: "bg-orange-500/15",
      sidebarActiveText: "text-orange-400",
      sidebarActiveBorder: "border-orange-500/40",
      buttonGradient: "from-orange-500 via-amber-600 to-red-600",
      buttonGradientHover: "hover:from-orange-400 hover:via-amber-500 hover:to-red-500",
      badgeBg: "bg-orange-500/20",
      badgeText: "text-orange-300",
      badgeBorder: "border-orange-500/40",
    },
    ambientTrack: "lofi_beats",
    ambientTrackTitle: "Warm Lo-Fi Vinyl Chords & Cozy Cafe Warmth",
  },
  "stage-neural-lab": {
    id: "stage-neural-lab",
    name: "Creative Synth & Neural Prompt Lab",
    shortName: "Neural Lab",
    emoji: "🔮",
    iconName: "Sliders",
    category: "workplace",
    themeFamily: "cyber",
    vibe: "Creative Flow",
    tagline: "Rapid prototyping, prompt tuning experiments, and dynamic workflow synthesis",
    buffMultiplier: "+35% Workflow Node Synthesis Precision",
    colors: {
      primary: "#a855f7", // purple-500
      secondary: "#6366f1", // indigo-500
      accentText: "text-purple-400",
      accentTextHover: "hover:text-purple-300",
      accentBg: "bg-purple-500",
      accentBgSoft: "bg-purple-500/10",
      accentBorder: "border-purple-500/30",
      accentBorderStrong: "border-purple-500/60",
      accentGlow: "shadow-[0_0_35px_rgba(168,85,247,0.22)]",
      ambientAura: "radial-gradient(ellipse 80% 50% at 50% -20%, rgba(168,85,247,0.18), transparent)",
      appBgGradient: "from-slate-950 via-[#18042b] to-slate-950",
      cardBg: "bg-slate-900/80",
      headerGradient: "from-purple-950/40 via-slate-900/90 to-slate-950/90",
      sidebarActiveBg: "bg-purple-500/15",
      sidebarActiveText: "text-purple-400",
      sidebarActiveBorder: "border-purple-500/40",
      buttonGradient: "from-purple-500 via-violet-600 to-indigo-600",
      buttonGradientHover: "hover:from-purple-400 hover:via-violet-500 hover:to-indigo-500",
      badgeBg: "bg-purple-500/20",
      badgeText: "text-purple-300",
      badgeBorder: "border-purple-500/40",
    },
    ambientTrack: "lofi_beats",
    ambientTrackTitle: "Analog Synth Waveform Generator",
  },
  "stage-secops-vault": {
    id: "stage-secops-vault",
    name: "Quantum SecOps Titanium Vault",
    shortName: "SecOps Vault",
    emoji: "🔐",
    iconName: "ShieldCheck",
    category: "workplace",
    themeFamily: "tactical",
    vibe: "Zero-Trust",
    tagline: "Zero-trust verification, security boundary audits, and compliance enforcement",
    buffMultiplier: "+40% RBAC & Data Privacy Leak Prevention",
    colors: {
      primary: "#f43f5e", // rose-500
      secondary: "#e11d48", // rose-600
      accentText: "text-rose-400",
      accentTextHover: "hover:text-rose-300",
      accentBg: "bg-rose-500",
      accentBgSoft: "bg-rose-500/10",
      accentBorder: "border-rose-500/30",
      accentBorderStrong: "border-rose-500/60",
      accentGlow: "shadow-[0_0_35px_rgba(244,63,94,0.22)]",
      ambientAura: "radial-gradient(ellipse 80% 50% at 50% -20%, rgba(244,63,94,0.18), transparent)",
      appBgGradient: "from-slate-950 via-[#23040e] to-slate-950",
      cardBg: "bg-slate-900/80",
      headerGradient: "from-rose-950/40 via-slate-900/90 to-slate-950/90",
      sidebarActiveBg: "bg-rose-500/15",
      sidebarActiveText: "text-rose-400",
      sidebarActiveBorder: "border-rose-500/40",
      buttonGradient: "from-rose-500 via-pink-600 to-red-600",
      buttonGradientHover: "hover:from-rose-400 hover:via-pink-500 hover:to-red-500",
      badgeBg: "bg-rose-500/20",
      badgeText: "text-rose-300",
      badgeBorder: "border-rose-500/40",
    },
    ambientTrack: "vault_pulse",
    ambientTrackTitle: "Quantum Resonance Lattice & EMP Shield",
  },
};

export const ALL_WORKPLACE_THEMES = Object.values(WORKPLACE_ZONE_THEMES);

export function getWorkplaceTheme(stageId?: string): WorkplaceZoneTheme {
  if (!stageId || !WORKPLACE_ZONE_THEMES[stageId]) {
    return WORKPLACE_ZONE_THEMES["stage-war-room"];
  }
  return WORKPLACE_ZONE_THEMES[stageId];
}
